// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_collect_300_stars = "CgkIyPb2xc8IEAIQDQ"; // <GPGSID>
        public const string achievement_collect_1500_stars = "CgkIyPb2xc8IEAIQEg"; // <GPGSID>
        public const string achievement_clear_700_level = "CgkIyPb2xc8IEAIQBQ"; // <GPGSID>
        public const string achievement_clear_500_level = "CgkIyPb2xc8IEAIQBA"; // <GPGSID>
        public const string achievement_clear_300_level = "CgkIyPb2xc8IEAIQAw"; // <GPGSID>
        public const string achievement_collect_500_stars = "CgkIyPb2xc8IEAIQDg"; // <GPGSID>
        public const string achievement_clear_10_level = "CgkIyPb2xc8IEAIQAA"; // <GPGSID>
        public const string achievement_clear_100_level = "CgkIyPb2xc8IEAIQAg"; // <GPGSID>
        public const string achievement_collect_2000_stars = "CgkIyPb2xc8IEAIQEw"; // <GPGSID>
        public const string achievement_collect_900_stars = "CgkIyPb2xc8IEAIQEA"; // <GPGSID>
        public const string achievement_collect_700_stars = "CgkIyPb2xc8IEAIQDw"; // <GPGSID>
        public const string achievement_clear_2500_level = "CgkIyPb2xc8IEAIQCQ"; // <GPGSID>
        public const string achievement_collect_200_stars = "CgkIyPb2xc8IEAIQDA"; // <GPGSID>
        public const string achievement_clear_1500_level = "CgkIyPb2xc8IEAIQBw"; // <GPGSID>
        public const string achievement_clear_50_level = "CgkIyPb2xc8IEAIQAQ"; // <GPGSID>
        public const string achievement_clear_2000_level = "CgkIyPb2xc8IEAIQCA"; // <GPGSID>
        public const string achievement_collect_1000_stars = "CgkIyPb2xc8IEAIQEQ"; // <GPGSID>
        public const string achievement_clear_1000_level = "CgkIyPb2xc8IEAIQBg"; // <GPGSID>
        public const string achievement_collect_3000_stars = "CgkIyPb2xc8IEAIQFA"; // <GPGSID>
        public const string achievement_clear_3000_level = "CgkIyPb2xc8IEAIQCg"; // <GPGSID>
        public const string achievement_collect_100_stars = "CgkIyPb2xc8IEAIQCw"; // <GPGSID>


    public const string achievement_clear_10_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement01"; // <GPGSID>
    public const string achievement_clear_50_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement02"; // <GPGSID>
    public const string achievement_clear_100_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement03"; // <GPGSID>
    public const string achievement_clear_300_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement04"; // <GPGSID>
    public const string achievement_clear_500_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement05"; // <GPGSID>
    public const string achievement_clear_700_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement06"; // <GPGSID>
    public const string achievement_clear_1000_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement07"; // <GPGSID>
    public const string achievement_clear_1500_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement08"; // <GPGSID>
    public const string achievement_clear_2000_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement09"; // <GPGSID>
    public const string achievement_clear_2500_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement10"; // <GPGSID>
    public const string achievement_clear_3000_level_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement11"; // <GPGSID>
    public const string achievement_collect_100_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement12"; // <GPGSID>
    public const string achievement_collect_300_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement13"; // <GPGSID>
    public const string achievement_collect_500_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement14"; // <GPGSID>
    public const string achievement_collect_700_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement15"; // <GPGSID>
    public const string achievement_collect_900_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement16"; // <GPGSID>
    public const string achievement_collect_1000_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement17"; // <GPGSID>
    public const string achievement_collect_3000_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement18"; // <GPGSID>
    public const string achievement_collect_5000_stars_IOS = "com.icecube.jewelsexploration.appstore.free.puzzle.achievement19"; // <GPGSID>
}

